#!/bin/bash
TARGET="/var/www/html/example-domain.com"
GIT_DIR="/home/dvalilis/bare/example-domain.git"
BRANCH="master"

while read oldrev newrev ref
do
	# only checking out the Branch stated above)
	if [ "$ref" = "refs/heads/$BRANCH" ];
	then
		echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
		git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
	else
		echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
	fi
done
