#!/bin/bash
#this is a postupdate script to populate the changes of the  git repo, to the 
#webroot folder of the site. You firstly create a bare repository on your home
#folder . then fill up the TARGET and GIT_DIR below, and the branch you 
#are working. Add this server as a remote git server on your working computer
#and each change you push will automatically be pushed to the target webroot.

TARGET="/var/www/html/example-domain.com"
GIT_DIR="/home/dvalilis/bare/example-domain.git"
BRANCH="master"

while read oldrev newrev ref
do
	# only checking out the Branch stated above)
	if [ "$ref" = "refs/heads/$BRANCH" ];
	then
		echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
		git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
	else
		echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
	fi
done
