---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /opt/docker/homer:/www/assets
    ports:
      - 9090:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
