# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
     - /media/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: sql-db-name
      MYSQL_USER: db-user-name
      MYSQL_PASSWORD: db-user-pass
    ports:
      -  3306:3306
